.\" Authors: Andre Masella
.TH aq-base 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-base \- Perform basic analysis in QIIME
.SH SYNOPSIS
.B aq-base
.SH DESCRIPTION
Performs basic QIIME analysis, including alpha diversity. It assumes you have a
.B mapping.txt 
file with all your sequences and that your sequences are named in QIIME's 
.I {SampleID::int}_{UID::int} 
in a file called
.B seq.fasta
format. This is a make-mediated process, so you can specify a target (e.g., 
.B aq-base otu_table.txt 
will produce only the OTU table).
.SH SEE ALSO
.BR axiome (1).
