.\" Authors: Andre Masella
.TH aq-cmplibs 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-cmplibs \- Compare pairs of libraries
.SH SYNOPSIS
.B aq-cmplibs
.I level
.SH DESCRIPTION
Take an OTU table of a particular flavour and plot each OTU at a point determine by the abundance in the two libraries. This gives an idea of whether two similar libraries are subsets of one another. All such plots are squished into one PDF.
.SH OPTIONS
.TP
level
A taxonomic level. This assumes there is a file \fBotu_table_summarized_\fIlevel\fB.txt\fR.
.SH SEE ALSO
.BR axiome (1).
