#!/usr/bin/env Rscript

options(error = quote(dump.frames("duleg-debug", TRUE)))

#Pull in arguments
args <- commandArgs(trailingOnly = TRUE)

#Should have exactly one argument, if not, complain
if (length(args) != 1) {
	print("Error: Exactly one parameter required (p cut-off value)")
	q()
}

#Set the plimit
plimit <- args[1]

#Sanity check on input
if ( plimit <= 0 || plimit >= 1 ) {
	print("Error: p value must be greater than 0, and less than 1")
	q()
}

#Load the labdsv library
library("labdsv")

#Read in and format otu table
print("Reading OTU table")
rawtable <- read.table("otu_table.txt", skip = 1, 
		comment.char = "", header = TRUE, row.names = 1, sep = "\t")
otutable <- t(rawtable[1:(ncol(rawtable) - 1)])

#Read in mapping
print("Reading mapping");
mapping <- t(read.table("mapping.txt", header = TRUE, comment.char = "", row.names = "X.SampleID", sep = "\t"))

# For non-numeric sample names, comment out the following line
colnames(mapping) <- paste("X", colnames(mapping), sep = "");

#Send to file duleg_p.txt where p is the supplied p value with the decimal point removed
pstr <- sub(".","",as.character(plimit),fixed=TRUE)
sink(paste("duleg_", pstr, ".txt", sep=""), append = FALSE)
sink()

for (x in 1 : nrow(mapping)) {
	name <- rownames(mapping)[x]
	fac.len <- length(levels(factor(as.matrix(mapping[x,])))) 
	if (fac.len < 2 || fac.len >= ncol(mapping)) {
		print(paste("Ignoring", name, "because all values are identical/different."))
		next
	}
	print(paste("Computing for", name))
	dis.bc <- dsvdis(otutable, 'bray/curtis')
	clust <- mapping[x, rownames(otutable)]
	d <- indval(otutable, clust)

#Save to our output file
	print("Saving")
	sink(paste("duleg_", pstr, ".txt", sep=""), append = TRUE)
	print(paste("For", name))
	#Run a summary using our p cutoff value supplied via command line argument
	summary(d, p=plimit, too.many=1000000, digits=3)
	sink()
	
	write.table(d$indcls, file = paste("duleg_", pstr, "_", name, "_indcls.txt", sep =""));
	write.table(d$indval, file = paste("duleg_", pstr, "_", name, "_indval.txt", sep =""));
	write.table(d$maxcls, file = paste("duleg_", pstr, "_", name, "_maxcls.txt", sep =""));
	write.table(d$pval, file = paste("duleg_", pstr, "_", name, "_pval.txt", sep =""));
	write.table(d$relabu, file = paste("duleg_", pstr, "_", name, "_relabu.txt", sep =""));
	write.table(d$relfrq, file = paste("duleg_", pstr, "_", name, "_relfrq.txt", sep =""));
}
