.\" Authors: Andre Masella
.TH aq-fasta-length 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-fasta-length \- Give lengths of FASTA sequences
.SH SYNOPSIS
.B aq-fasta-length
.I file.fasta ...
.SH DESCRIPTION
Print the name of each sequence in a FASTA file and the length of the sequence itself.
.SH OPTIONS
.TP
file.fasta
The input files to be counted.
.SH SEE ALSO
.BR autoqiime (1).
