.\" Authors: Andre Masella
.TH aq-fastq2oldillumina 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-fastq2oldillumina \- Convert new Illumina files to old Illumina files
.SH SYNOPSIS
.B aq-fastq2oldillumina
[
.B \-j
] 
.B \-f 
.I file.fastq
.SH DESCRIPTION
Convert a CASAVA 1.5+ FASTQ file to a CASAVA 1.3 file colon-delimited file.
.SH OPTIONS
.TP
\-f
The FASTQ file to be examined.
.TP
\-j
The input file is compressed with
.SH SEE ALSO
.BR autoqiime (1).
