.\" Authors: Andre Masella
.TH aq-inst-cran 1 "February 2012" "1.3" "USER COMMANDS"
.SH NAME 
aq-inst-cran \- Install R CRAN packages needed by AXIOME
.SH SYNOPSIS
.B aq-inst-cran
.SH DESCRIPTION
Installs the R packages needed by AXIOME's various analyses. Since R packages are not necessarily managed by the package manager, this script will forcibly install them.
.SH SEE ALSO
.BR R (1),
.BR axiome (1).
