#!/bin/sh

if [ $# -ne 1 ]
then
	echo $0 seq_otus.txt \< otu_ids
	echo Determine the contribution of the various libraries to the specified OTUs
	exit 1
fi
tr -d '>' | sort -n | aq-joinn /dev/stdin "$1" | cut -f 3- | sed -e 's/_[^\t ]*\t/\n/g; s/_[^\t ]*$//g' | sort | uniq -c
