.\" Authors: Andre Masella
.TH aq-libcontrib 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-libcontrib \- Determine which libraries are contribution to a set of OTUs.
.SH SYNOPSIS
.B aq-libcontrib
.I seq_otus.txt
.SH DESCRIPTION
Given a list of OTUs on standard input and the \fBseq_otus.txt\fR, a table of the number of sequences contributed by each library to this list is provided.
.SH OPTIONS
.TP
seq_otus.txt
The \fBseq_otus.txt\fR file created by \fBpick_otus.py\fR in QIIME.
.SH SEE ALSO
.BR autoqiime (1).
