.\" Authors: Michael Hall
.TH aq-mothur-alpha 1 "July 2012" "1.6" "USER COMMANDS"
.SH NAME 
aq-mothur-alpha \- Plot Mothur alpha rarefactions in R
.SH SYNOPSIS
.B aq-mothur-alpha filename
.SH DESCRIPTION
Plot mothur's alpha rarefaction data using R. A \fBmapping.extra\fR file must be supplied to fill in the plot's legend. This is automatically set up by AXIOME. Outputs \fBalpha_<method>.pdf\fR, where <method> is the calc used by mothur.
.SH SEE ALSO
.BR axiome (1).
