#!/bin/sh

if [ $# -ne 2 ]
then
	echo Keep top n taxa from a summarized OTU table: $0 n otu_table.txt
	exit 1
fi

awk 'NR == 1 { print 32767, $0;} NR > 1 {sum = 0; for (i=2; i < NF; i++){sum += $i} print sum,$0;}' "$2" | sort -nr | cut -f 2- -d " " | head -n $(($1+1))
