.\" Authors: Andre Masella
.TH aq-otusum 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-otusum \- Print total counts for each OTU
.SH SYNOPSIS
.B aq-otusum
.I otu_table.tab
.SH DESCRIPTION
Produce a combined count for each OTU. 
.SH OPTIONS
.TP
otu_table.tab
The OTU table to sum. Must be in tab delimited format, not BIOM format.
.SH SEE ALSO
.BR axiome (1).
