.\" Authors: Andre Masella
.TH aq-orderotu 1 "March 2012" "1.4" "USER COMMANDS"
.SH NAME 
aq-orderotu \- Reorder the columns in an OTU table TO BE IN ORDER
.SH SYNOPSIS
.B aq-orderotu
.I otu_table.txt
.SH DESCRIPTION
QIIME unhelpfully puts the columns of an OTU table into alphabetical order, making it a pain to marry the data to anything else. This script spits out an OTU table with the columns in the order you would expect them to be.
.SH OPTIONS
.TP
otu_table.txt
The OTU table to unfrack.
.SH SEE ALSO
.BR autoqiime (1).
