.\" Authors: Andre Masella
.TH aq-otuhistogram 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-otuhistogram \- Produce a histogram of OTU sizes
.SH SYNOPSIS
.B aq-otuhistogram
.I otu_table.txt
.SH DESCRIPTION
Produces a histogram for the sizes of OTUs, combining all samples in an OTU table.
.SH OPTIONS
.TP
otu_table.txt
The OTU table to analyse.
.SH SEE ALSO
.BR autoqiime (1).
