.\" Authors: Andre Masella
.TH aq-oldillumina2fastq 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-oldillumina2fastq \- Convert old Illumina files into FASTQ
.SH SYNOPSIS
.B aq-oldillumina2fastq
.SH DESCRIPTION
An input file from CASAVA 1.3 is provided either on standard input or the command line and a FASTQ format file, compressed with 
.BR bzip2 (1)
is produced on standard output.
.SH SEE ALSO
.BR autoqiime (1).
