.\" Authors: Andre Masella
.TH aq-otuplothistogram 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-otuplothistogram \- Produce a combined rank-abundance curve
.SH SYNOPSIS
.B aq-otuplothistogram
.SH DESCRIPTION
Produce a histogram of OTU size combined across all samples.
.SH SEE ALSO
.BR axiome (1).
