#!/usr/bin/env Rscript
options(error = quote(dump.frames("pca-debug", TRUE)))

print("Reading OTU table");
otutable <- read.table("otu_table_ordered_columns.txt", skip = 1, comment.char = "", header = TRUE, row.names = 1, sep = "\t");
print("Reading mapping");
mapping <- read.table("mapping.txt", header = TRUE, comment.char = "", row.names = "X.SampleID", sep = "\t")
print("Reading mapping extra");
extra <- read.table("mapping.extra", header = TRUE,
    comment.char = "", row.names = "X.SampleID", sep = "\t")
print("Reading header");
interest <- read.table("headers.txt")[1,] == "TRUE";
print("Computing PCA");

for(i in 0 : length(interest)) {
	if (interest[i] && length(levels(factor(as.matrix(mapping[, i])))) == 1) {
		interest[i] <- FALSE
		print(paste("Ignoring", colnames(mapping)[i], "because all values are identical."))
	}
}
newmapping <- t(mapping[,interest]);

# For non-numeric sample names, comment out the following line
colnames(newmapping) <- paste("X", rownames(mapping), sep = "");
rownames(newmapping) <- colnames(mapping)[interest];

d <- rbind(otutable[,seq(1,ncol(otutable)-1)], newmapping);
p <- prcomp(t(d), scale = TRUE);

pdf("biplot.pdf");

print("Making Scree plot");
plot(p);

print("Making MDS plot");
plot(p$x, asp = p$sdev[2]/p$sdev[1], col = as.matrix(extra[ ,"Colour"]));
text(x = p$x[, "PC1"], y = p$x[, "PC2"], labels = extra[ ,"Description"], col = as.matrix(extra[ ,"Colour"]));

print("Making biplot");
contrib <- apply(p$rotation, 1, function(x) {sqrt(sum(x[1:2]^2));});

# What variables (rows) do you want to display as arrows?
#useful <- contrib > (mean(contrib) + 2*sd(contrib));
useful <- colnames(mapping)[interest];
if (length(useful) > 1) {
	biplot(p$x[, c("PC1", "PC2")], p$rotation[useful, c("PC1", "PC2")], xlabs = extra[, "Description"], asp = p$sdev[2]/p$sdev[1]);
}
