.\" Authors: Andre Masella
.TH aq-pca 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-pca \- Perform PCA in R
.SH SYNOPSIS
.B aq-pca
.SH DESCRIPTION
Perform a principal component analysis using R. This includes taxa and any numerical properties in the \fBmapping.txt\fR file. It is expected that there be an OTU table called \fBotu_table_ordered_columns.txt\fR, the colour and label for every point in \fBmapping.extra\fR, and a list of which properties from \fBmapping.txt\fR to use in a file called \fBheaders.txt\fR. This is automatically set up by AutoQIIME.
.SH SEE ALSO
.BR autoqiime (1), aq-orderotu (1).
