#!/bin/bash

if [ $# != 2 ]
then
	echo Usage: $0 rareified_otu_table.txt otu_table.tab
	exit 1
fi

aq-joinn "$1" "$2" | awk -F '\t' 'NR == 1 {print $1}  NR > 1 { for (i = 1; i <=(NF/2); i++) {printf("%s\t", $i);} printf("%s\n", $NF);}'
