.\" Authors: Andre Masella
.TH aq-sort-fasta 1 "October 2011" "1.2" "USER COMMANDS"
.SH NAME 
aq-sort-fasta \- Sort a FASTA file by length
.SH SYNOPSIS
.B aq-sort-fasta
[ 
.I file 
]
.SH DESCRIPTION
Sort the sequences in a FASTA file by length, from longest to shortest.
.SH OPTIONS
.TP
file
The input file(s) to be sorted. If not supplied, data is read from standard input.
.SH SEE ALSO
.BR axiome (1).
