.\" Authors: Michael Hall
.TH aq-venn 1 "January 2013" "1.6" "USER COMMANDS"
.SH NAME 
aq-venn \- Perform Venn diagram plotting in R
.SH SYNOPSIS
.B aq-venn -i input -o output -m mapping
.SH DESCRIPTION
Plot Venn diagrams using the metadata clusters in the mapping file. Plots the OTU sequence abundance for each category. For example, if your mapping file contains a category "Month" with values "January" and "February", the Venn diagram will show how many sequences were found only in January, how many were found only in February, and how many were found in both January and February. For this to function, the Vennerable library must be installed. It is available at https://r-forge.r-project.org/projects/vennerable/.
.SH SEE ALSO
.BR axiome (1).
