.\" Authors: Andre Masella, Michael Hall
.TH autoqiime 1 "July 2012" "1.6" "USER COMMANDS"
.SH NAME
autoqiime \- Automation toolkit for QIIME
.SH SYNOPSIS
.B autoqiime
.I input.aq
.SH DESCRIPTION
AXIOME is a way of automating tedious and error-prone analysis with the QIIME toolkit. Since it was formely known as AutoQIIME, this command is provided to ease transition. It will be removed. Please use
.BR axiome (1).
