#!/bin/bash
TAXASS=$(mktemp)
OTU=$(mktemp)
SEQ=$(mktemp)
echo Preparing taxonomy assignments...
sort -k 1b,1 rdp_assigned_taxonomy/seq.fasta_rep_set_tax_assignments.txt > $TAXASS
echo Preparing OTU table...
sort -k 1b,1 otu_table.txt > $OTU
echo Preparing sequences...
awk '/^>/ {if (name) {print name, seq;} name = substr($0,2); seq = ""; } $0!~/^>/{ seq = seq $0;}' seq.fasta | sort -k 1b,1 > $SEQ

echo Joining...
awk -F "\t" 'NR == 2 {printf("#SeqID\tOTU ID\tConsensus Lineage"); for (i = 2; i < NF; i++) { printf ("\t%s", $i); } printf("\tSequence\n");}' otu_table.txt > otu_sources.txt
join $TAXASS $OTU | awk '{ printf("%s\t%s\t%s\t", $2, $1, $3); for (i = 5; i < NF - 1; i++) { printf("%s\t", $i);} printf("%s\n", $(NF-1)); }' | sort -k 1b,1 | join - $SEQ | sort -k 2 >> otu_sources.txt
rm -f $TAXASS $OTU $SEQ
