#!/bin/bash

(head -n 2 "$1"; awk -F '\t' 'NR > 2 {s = 0; for (i = 2; i < NF; i++) { s += $i; } print s, $0; }' "$1" | sort -nr | head -n 32000 ) | awk 'NR == 2 { for (i = 2; i < NF; i++) { name[i] = $i; } } NR > 2 { for (i = 2; i < NF; i++) { v[i] = v[i] "," $i } } END { print length(name)",samples"; print (NR - 2) ",OTUs"; for (i = 2; i < NR; i++) { printf(",Q"); } printf("\n"); for (x in name) { print name[x], v[x]; } }'
