#!/bin/bash

if [ $# -lt 2 ]
then
	echo Usage: $0 otufile binboundary1 binboundary2 ...
	exit 1
fi

if [ ! -r "$1" ]
then
	echo "$1 does not appear to be a file."
	exit 1
fi

SRC="$1"
shift

echo 'Bin 1 = (-∞,'$1')'
awk '$1 ~ /^[0-9]*$/ { v = 0; for (i = 2; i < NF; i++) { v += $i; } if (v < '$1') {print}} $1 !~ /^[0-9]*$/ {print}' "$SRC" > "$SRC".bin1

i=2
while [ $# -gt 1 ]
do
	if [ $1 -ge $2 ]
	then
		echo "You must give me the bin boundaries in ascending order, but $1 ≮ $2 and I give up."
		exit 1
	fi
	echo 'Bin '$i' = ['$1', '$2')'
	awk '$1 ~ /^[0-9]*$/ { v = 0; for (i = 2; i < NF; i++) { v += $i; } if (v >= '$1' && v < '$2') {print}} $1 !~ /^[0-9]*$/ {print}' "$SRC" > "$SRC".bin$i
	i=$(($i+1))
	shift
done

echo 'Bin '$i' = ['$1', ∞)'
awk '$1 ~ /^[0-9]*$/ { v = 0; for (i = 2; i < NF; i++) { v += $i; } if (v >= '$1') {print}} $1 !~ /^[0-9]*$/ {print}' "$SRC" > "$SRC".bin$i
