#!/bin/bash

if [ $# != 2 ]
then
	echo $0 blah_rep_set.fasta otu_table.txt 1>&2
	exit 1
fi

otuwithseqs "$1" "$2" | awk 'BEGIN { FS = "\t" } NR == 1 {print $0} NR == 2 { for (i = 1; i < NF - 1; i++) { printf("%s\t", $i); } printf("Consensus Lineage\n"); } NR > 2 { printf("%s", $1); for (i = 2; i < NF - 1; i++) { printf("\t%s", $i); } printf("\t%s;%s\n", $1, $NF); }'
