#!/bin/bash

if [ $# != 2 ]
then
	echo $0 blah_rep_set.fasta otu_table.txt 1>&2
	exit 1
fi

export LC_ALL=C
awk 'BEGIN { print "#OTU ID\tReprSequence"; } /^>/ {if (name) { print name "\t" seq;} name = substr($1, 2); seq = ""; } $1 !~ /^>/ { seq = seq $0; } END { if (name) { print name "\t" seq; }}' "$1" | sort -n -t \t | join -t '	' -a 1 "$2" -
